# file-downloader/docker-compose.yml
version: '3'

services:
  file-downloader:
    build: .
    container_name: file-downloader
    ports:
      - "3000:3000"
    volumes:
      - /mnt/Pool1/Network_Drive/downloads:/downloads
      - ./logs:/logs
    restart: unless-stopped
